// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB77gitk6rer-sxcEOAeezbvDeQdBhT_9k',
    appId: '1:51789132308:web:7cb1610ec48cfc424f6d01',
    messagingSenderId: '51789132308',
    projectId: 'slaap-kanki',
    authDomain: 'slaap-kanki.firebaseapp.com',
    storageBucket: 'slaap-kanki.appspot.com',
    measurementId: 'G-K1LGV6DMGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzhZ4QbwU5RimwCcLkIwxyyfMqcrQPx8I',
    appId: '1:51789132308:android:ebbcc21a576dd6d34f6d01',
    messagingSenderId: '51789132308',
    projectId: 'slaap-kanki',
    storageBucket: 'slaap-kanki.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa3L9YlcDuOArt0st0X4QBkEfHzgSvYT8',
    appId: '1:51789132308:ios:5be0b9bac73144184f6d01',
    messagingSenderId: '51789132308',
    projectId: 'slaap-kanki',
    storageBucket: 'slaap-kanki.appspot.com',
    iosBundleId: 'com.example.slaap',
  );
}
